---
# Pipeline to run the hybrid workflow PowerShell script
trigger: none
pool:
  vmImage: 'windows-latest'

steps:
- task: PowerShell@2
  displayName: Run hybrid workflow
  inputs:
    filePath: '$(System.DefaultWorkingDirectory)/Flyway.hybrid/Hybrid-Apply-EFCoreToFwdDev.ps1'
    pwsh: true
