[environments.development]
url = "jdbc:sqlserver://localhost;instanceName=Bartender;databaseName=Demo-Hybrid-Flyway;encrypt=true;integratedSecurity=true;trustServerCertificate=true"
displayName = "Development"

[environments.shadow]
url = "jdbc:sqlserver://localhost;instanceName=bartender;databaseName=Demo-Hybrid-Shadow;encrypt=true;integratedSecurity=true;trustServerCertificate=true"
displayName = "Shadow"

[environments.PROD]
url = "jdbc:sqlserver://localhost;instanceName=bartender;databaseName=Demo-Hybrid-Production;encrypt=true;integratedSecurity=true;trustServerCertificate=true"
displayName = "Production"