---
# Pipeline to run the simple workflow PowerShell script
trigger: none
pool:
  vmImage: 'windows-latest'

steps:
- task: PowerShell@2
  displayName: Run simple workflow
  inputs:
    filePath: '$(System.DefaultWorkingDirectory)/Flyway.simple/Simple-Convert-EFMigrationsToFlyway.ps1'
    pwsh: true
