---
# Pipeline to run the inverted workflow PowerShell script
trigger: none
pool:
  vmImage: 'windows-latest'

steps:
- checkout: self
  persistCredentials: true
- task: PowerShell@2
  displayName: Run inverted workflow
  inputs:
    filePath: '$(System.DefaultWorkingDirectory)/02.Flyway.inverted/Convert-EFMigrationsToSchemaModel.ps1'
    pwsh: true

- script: |
    git config user.name "$(Build.RequestedFor)"
    git config user.email "$(Build.RequestedForEmail)"
    git add .
    git commit -m "chore: update Flyway artifacts" || echo "Nothing to commit"
    git push
  displayName: Commit Flyway artifacts
