[environments.development]
url = "jdbc:sqlserver://localhost;instanceName=Bartender;databaseName=Demo-Simple-Flyway;encrypt=true;integratedSecurity=true;trustServerCertificate=true"
displayName = "Dev"

[environments.shadow]
url = "jdbc:sqlserver://localhost;instanceName=bartender;databaseName=Demo-Simple-Shadow;encrypt=true;integratedSecurity=true;trustServerCertificate=true"

[environments.PROD]
url = "jdbc:sqlserver://localhost;instanceName=bartender;databaseName=Demo-Simple-production;encrypt=true;integratedSecurity=true;trustServerCertificate=true"
